import {isSafari} from 'react-device-detect'
import currentSeasonNG1 from './board/currentSeasonNG1.png'
import NG2NG3 from './board/NG2NG3.png'
import season23 from './board/season23.png'
import rainforestCardBack from './cards/rainforestCards/rainforestCard-Back.png'
import blight from './cards/rainforestCards/advancedRainforestCards/blight.jpg'
import coincapFungi from './cards/rainforestCards/advancedRainforestCards/coincapFungi.jpg'
import goldenLionTamarinMP from './cards/rainforestCards/advancedRainforestCards/goldenLionTamarin-MP.jpg'
import goldenLionTamarinWL from './cards/rainforestCards/advancedRainforestCards/goldenLionTamarin-WL.jpg'
import goliathBirdEaterMP from './cards/rainforestCards/advancedRainforestCards/goliathBirdEater-MP.jpg'
import goliathBirdEaterWL from './cards/rainforestCards/advancedRainforestCards/goliathBirdEater-WL.jpg'
import harmoniaMantleWL1 from './cards/rainforestCards/advancedRainforestCards/harmoniaMantle-WL1.jpg'
import harmoniaMantleWL2 from './cards/rainforestCards/advancedRainforestCards/harmoniaMantle-WL2.jpg'
import hoatzinMP from './cards/rainforestCards/advancedRainforestCards/hoatzin-MP.jpg'
import hoatzinWL from './cards/rainforestCards/advancedRainforestCards/hoatzin-WL.jpg'
import howlerMonkeyMP from './cards/rainforestCards/advancedRainforestCards/howlerMonkey-MP.jpg'
import howlerMonkeyWL from './cards/rainforestCards/advancedRainforestCards/howlerMonkey-WL.jpg'
import jaguarMP from './cards/rainforestCards/advancedRainforestCards/jaguar-MP.jpg'
import jaguarWL from './cards/rainforestCards/advancedRainforestCards/jaguar-WL.jpg'
import lianas from './cards/rainforestCards/advancedRainforestCards/lianas.jpg'
import lightning from './cards/rainforestCards/advancedRainforestCards/lightning.jpg'
import orchid from './cards/rainforestCards/advancedRainforestCards/orchid.jpg'
import pitcherPlant from './cards/rainforestCards/advancedRainforestCards/pitcherPlant.jpg'
import pygmyMarmosetWL1 from './cards/rainforestCards/advancedRainforestCards/pygmyMarmoset-WL1.jpg'
import pygmyMarmosetWL2 from './cards/rainforestCards/advancedRainforestCards/pygmyMarmoset-WL2.jpg'
import bromelia from './cards/rainforestCards/basicRainforestCards/bromelia.jpg'
import canopy01 from './cards/rainforestCards/basicRainforestCards/canopy01.jpg'
import canopy02 from './cards/rainforestCards/basicRainforestCards/canopy02.jpg'
import canopy03 from './cards/rainforestCards/basicRainforestCards/canopy03.jpg'
import canopy11 from './cards/rainforestCards/basicRainforestCards/canopy11.jpg'
import canopy12 from './cards/rainforestCards/basicRainforestCards/canopy12.jpg'
import canopy13 from './cards/rainforestCards/basicRainforestCards/canopy13.jpg'
import canopy14 from './cards/rainforestCards/basicRainforestCards/canopy14.jpg'
import canopy15 from './cards/rainforestCards/basicRainforestCards/canopy15.jpg'
import canopy16 from './cards/rainforestCards/basicRainforestCards/canopy16.jpg'
import canopy21 from './cards/rainforestCards/basicRainforestCards/canopy21.jpg'
import canopy22 from './cards/rainforestCards/basicRainforestCards/canopy22.jpg'
import disease from './cards/rainforestCards/basicRainforestCards/disease.jpg'
import drought from './cards/rainforestCards/basicRainforestCards/drought.jpg'
import emeraldTreeBoaMP from './cards/rainforestCards/basicRainforestCards/emeraldTreeBoa-MP.jpg'
import emeraldTreeBoaWL from './cards/rainforestCards/basicRainforestCards/emeraldTreeBoa-WL.jpg'
import fern from './cards/rainforestCards/basicRainforestCards/fern.jpg'
import fire from './cards/rainforestCards/basicRainforestCards/fire.jpg'
import kinkajouMP from './cards/rainforestCards/basicRainforestCards/kinkajou-MP.jpg'
import kinkajouWL from './cards/rainforestCards/basicRainforestCards/kinkajou-WL.jpg'
import leafCutterAntsMP from './cards/rainforestCards/basicRainforestCards/leafCutterAnts-MP.jpg'
import leafCutterAntsWL from './cards/rainforestCards/basicRainforestCards/leafCutterAnts-WL.jpg'
import monstera from './cards/rainforestCards/basicRainforestCards/monstera.jpg'
import poisonDartFrogMP from './cards/rainforestCards/basicRainforestCards/poisonDartFrog-MP.jpg'
import poisonDartFrogWL from './cards/rainforestCards/basicRainforestCards/poisonDartFrog-WL.jpg'
import rain from './cards/rainforestCards/basicRainforestCards/rain.jpg'
import seed from './cards/rainforestCards/basicRainforestCards/seed.jpg'
import slothMP from './cards/rainforestCards/basicRainforestCards/sloth-MP.jpg'
import slothWL from './cards/rainforestCards/basicRainforestCards/sloth-WL.jpg'
import sun from './cards/rainforestCards/basicRainforestCards/sun.jpg'
import toucanMP from './cards/rainforestCards/basicRainforestCards/toucan-MP.jpg'
import toucanWL from './cards/rainforestCards/basicRainforestCards/toucan-WL.jpg'
import trunk01 from './cards/rainforestCards/basicRainforestCards/trunk01.jpg'
import trunk02 from './cards/rainforestCards/basicRainforestCards/trunk02.jpg'
import trunk03 from './cards/rainforestCards/basicRainforestCards/trunk03.jpg'
import trunk04 from './cards/rainforestCards/basicRainforestCards/trunk04.jpg'
import trunk05 from './cards/rainforestCards/basicRainforestCards/trunk05.jpg'
import trunk11 from './cards/rainforestCards/basicRainforestCards/trunk11.jpg'
import trunk12 from './cards/rainforestCards/basicRainforestCards/trunk12.jpg'
import trunk13 from './cards/rainforestCards/basicRainforestCards/trunk13.jpg'
import trunk14 from './cards/rainforestCards/basicRainforestCards/trunk14.jpg'
import trunk15 from './cards/rainforestCards/basicRainforestCards/trunk15.jpg'
import trunk16 from './cards/rainforestCards/basicRainforestCards/trunk16.jpg'
import trunk17 from './cards/rainforestCards/basicRainforestCards/trunk17.jpg'
import trunk18 from './cards/rainforestCards/basicRainforestCards/trunk18.jpg'
import trunk21 from './cards/rainforestCards/basicRainforestCards/trunk21.jpg'
import trunk22 from './cards/rainforestCards/basicRainforestCards/trunk22.jpg'
import trunk23 from './cards/rainforestCards/basicRainforestCards/trunk23.jpg'
import trunk24 from './cards/rainforestCards/basicRainforestCards/trunk24.jpg'
import trunk25 from './cards/rainforestCards/basicRainforestCards/trunk25.jpg'
import sBromelia from './cards/seedCards/bromelia.jpg'
import sCanopy01 from './cards/seedCards/canopy01.jpg'
import sCanopy11 from './cards/seedCards/canopy11.jpg'
import sCanopy21 from './cards/seedCards/canopy21.jpg'
import sFern from './cards/seedCards/fern.jpg'
import sMonstera from './cards/seedCards/monstera.jpg'
import sRain from './cards/seedCards/rain.jpg'
import seedCardBack from './cards/seedCards/seedCard-back.jpg'
import sSun from './cards/seedCards/sun.jpg'
import sTrunk01 from './cards/seedCards/trunk01.jpg'
import sTrunk11 from './cards/seedCards/trunk11.jpg'
import sTrunk12 from './cards/seedCards/trunk12.jpg'
import sTrunk21 from './cards/seedCards/trunk21.jpg'
import sTrunk22 from './cards/seedCards/trunk22.jpg'
import seasonOfCleansing from './cards/shiftingSeasons/seasonOfCleansing.jpg'
import seasonOfDanger from './cards/shiftingSeasons/seasonOfDanger.jpg'
import seasonOfDiversity from './cards/shiftingSeasons/seasonOfDiversity.jpg'
import seasonOfFecundity from './cards/shiftingSeasons/seasonOfFecundity.jpg'
import seasonOfHunting from './cards/shiftingSeasons/seasonOfHunting.jpg'
import seasonOfLeaves from './cards/shiftingSeasons/seasonOfLeaves.jpg'
import seasonOfMating from './cards/shiftingSeasons/seasonOfMating.jpg'
import seasonOfRot from './cards/shiftingSeasons/seasonOfRot.jpg'
import seasonOfSky from './cards/shiftingSeasons/seasonOfSky.jpg'
import seasonOfStature from './cards/shiftingSeasons/seasonOfStature.jpg'
import seasonOfSymbiotes from './cards/shiftingSeasons/seasonOfSymbiotes.jpg'
import shiftingSeasonBack from './cards/shiftingSeasons/shiftingSeason-back.jpg'
import startingTrunkBack from './cards/startingTrunks/startingTrunk-back.jpg'
import startingTrunk from './cards/startingTrunks/startingTrunk.jpg'
import coverArtwork from './canopy-cover-artwork.png'
import arrowGreen from './menus/arrow-green.png'
import arrowOrange from './menus/arrow-orange.png'
import arrowWhite from './menus/arrow-white.png'
import buttonArrow from './menus/button-arrow.png'
import circleMetal from './menus/circle-metal.png'
import buttonBlack from './menus/menu-black.png'
import buttonBlue from './menus/menu-blue.png'
import buttonYellow from './menus/menu-gold.png'
import buttonGreen from './menus/menu-green.png'
import buttonGrey from './menus/menu-grey.png'
import buttonRed from './menus/menu-red.png'
import textureGrey from './menus/texture-grey.jpg'
import titleBlack from './menus/title-black.png'
import titleBlue from './menus/title-blue.png'
import titleGreen from './menus/title-green.png'
import titleGrey from './menus/title-grey.png'
import titleOrange from './menus/title-orange.png'
import titleWhite from './menus/title-white.png'
import titleYellow from './menus/title-yellow.png'
import scoreBackground from './score-background.png'
import scoreIcon from './score-icon.png'

const Images = {
  currentSeasonNG1, NG2NG3, season23,
  rainforestCardBack, blight, coincapFungi, goldenLionTamarinMP, goldenLionTamarinWL, goliathBirdEaterMP, goliathBirdEaterWL,
  harmoniaMantleWL1, harmoniaMantleWL2, hoatzinMP, hoatzinWL, howlerMonkeyMP, howlerMonkeyWL, jaguarMP, jaguarWL, lianas, lightning,
  orchid, pitcherPlant, pygmyMarmosetWL1, pygmyMarmosetWL2,
  bromelia, canopy01, canopy02, canopy03, canopy11, canopy12, canopy13, canopy14, canopy15, canopy16, canopy21, canopy22,
  disease, drought, emeraldTreeBoaMP, emeraldTreeBoaWL, fern, fire, kinkajouMP, kinkajouWL, leafCutterAntsMP, leafCutterAntsWL,
  monstera, poisonDartFrogMP, poisonDartFrogWL, rain, seed, slothMP, slothWL, sun, toucanMP, toucanWL,
  trunk01, trunk02, trunk03, trunk04, trunk05, trunk11, trunk12, trunk13, trunk14, trunk15, trunk16, trunk17, trunk18, trunk21, trunk22, trunk23, trunk24, trunk25,
  sBromelia, sCanopy01, sCanopy11, sCanopy21, sFern, sMonstera, sRain, seedCardBack, sSun, sTrunk01, sTrunk11, sTrunk12, sTrunk21,sTrunk22,
  seasonOfCleansing, seasonOfDanger, seasonOfDiversity, seasonOfFecundity, seasonOfHunting, seasonOfLeaves, seasonOfMating, seasonOfRot, seasonOfSky, seasonOfStature, seasonOfSymbiotes, shiftingSeasonBack,
  startingTrunkBack, startingTrunk,
  arrowGreen, arrowOrange, arrowWhite, buttonArrow,
  buttonBlack, buttonBlue, buttonGreen, buttonGrey, buttonRed, buttonYellow, textureGrey,
  circleMetal, titleBlack, titleBlue, titleGreen, titleGrey, titleOrange, titleWhite, titleYellow,
  coverArtwork, scoreBackground, scoreIcon
}

if (!isSafari) {
  for (const image in Images) {
    const match = Images[image].match(/(.*)\.(jpg|png)$/)
    if (match) {
      Images[image] = match[1] + '.webp'
    }
  }
}

export default Images